"use client"

import Sidebar from "@/components/organisms/sidebarLeft";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "@/components/molecules/header";
import SidebarRight from "@/components/organisms/sidebarRight";
import DashboardCards from "@/components/molecules/dashboardCards";
import { useState } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [collapsed, setSidebarCollapsed] = useState(true);
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex md:justify-evenly lg:justify-stretch m-0 gap-0">
          <Sidebar
            collapsed={collapsed}
            setCollapsed={() => setSidebarCollapsed((prev) => !prev)}
          />
          <div className="w-[80%] lg:flex-grow pt-3">
            <Header />
            <div className="lg:flex  bg-[#EDEDED] md:block">
              <div className="lg:w-[70%] md:w-100 lg:flex-grow  pl-5 p-3 ">{children}</div>
              <SidebarRight  />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
